// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLuIVjgN_INm9_5lwrJeDMMwUjeRacGk',
    appId: '1:472966036739:web:73c8b3886151bd5d86fd36',
    messagingSenderId: '472966036739',
    projectId: 'project-42382',
    authDomain: 'project-42382.firebaseapp.com',
    storageBucket: 'project-42382.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQV69zm6GQ0jCrvi25ZBKdNwRDYWjp-Y8',
    appId: '1:472966036739:android:da3faf7d7765f1de86fd36',
    messagingSenderId: '472966036739',
    projectId: 'project-42382',
    storageBucket: 'project-42382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC011PqdNeJkNv-ntal-YTcSijtFBVDP44',
    appId: '1:472966036739:ios:c5720451398e83fe86fd36',
    messagingSenderId: '472966036739',
    projectId: 'project-42382',
    storageBucket: 'project-42382.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC011PqdNeJkNv-ntal-YTcSijtFBVDP44',
    appId: '1:472966036739:ios:c5720451398e83fe86fd36',
    messagingSenderId: '472966036739',
    projectId: 'project-42382',
    storageBucket: 'project-42382.firebasestorage.app',
    iosBundleId: 'com.codeforany.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgLuIVjgN_INm9_5lwrJeDMMwUjeRacGk',
    appId: '1:472966036739:web:ed4e97e8cd27a73886fd36',
    messagingSenderId: '472966036739',
    projectId: 'project-42382',
    authDomain: 'project-42382.firebaseapp.com',
    storageBucket: 'project-42382.firebasestorage.app',
  );
}
